CREATE TABLE IF NOT EXISTS role (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    username VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role_id BIGINT NOT NULL REFERENCES role(id),
    blocked BOOL,
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS token (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    token VARCHAR,
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    message TEXT,
    user_id BIGINT NOT NULL REFERENCES users(id),
    PRIMARY KEY (id)
);